apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress-svc
spec:
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress_image
        imagePullPolicy: Never
        name: wordpress
        ports:
        - containerPort: 5050