apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.105
  ports:
    - name: ftps
      port: 21
      protocol: TCP
      targetPort: 21
    - name: ftps-passive
      protocol: TCP
      port: 30021
      targetPort: 30021
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps_image
        name: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30021